<?php
echo '<!DOCTYPE html>';
echo '<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">';
echo '<head>';
echo '<meta charset="utf-8"/>';
echo '<title>Front Page</title>';
echo '<link rel="stylesheet" href="theme.css" type="text/css" />';
echo '</head>';
echo '<body>';
echo '<div class="header">';
echo '';
echo '<!--#include virtual="ssi/lab_assignment_nav.txt"-->';
echo '';
echo '<div class="MainContent">';
echo '';
echo '<!--#include virtual="ssi/SubContent1.txt"-->';
echo '';
echo '<div class="SubContent2">';
echo '<div class="GMU">';
echo '<img src="https://i.ibb.co/qMbFcZs/profile.png" alt="Profile Picture" />';
echo '<p>(Build-in Function Output)</p>';
echo '</div>';
echo '';
echo '<div class="Summary">';
echo '<h4>Summary</h4>';
echo '<ul>';
echo '<li>Personal</li>';
echo '<ul>';
echo '<li>Fast Learner</li>';
echo '<li>Introvert</li>';
echo '<li>Critical Thinking</li>';
echo '</ul>';
echo '<li>Academic</li>';
echo '<ul>';
echo '<li>3.5 GPA or higher</li>';
echo '<li>Perfect Attendance</li>';
echo '<li>Knowledge driven</li>';
echo '</ul>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="Paragraph">';
echo '<p>Hi my name is Nhat Nguyen.';
echo 'I am going by Nate with my friends to avoid being called gnat.';
echo 'I was born in Ho Chi Minh City, Vietnam and moved to the States since 2007.';
echo 'I have lived in Virginia ever since. I am a transfer student from NVCC.';
echo 'I often traveled throughout South East Asia countries when I was young; Singapore, Malaysia Thailand, Japan, China.';
echo 'However, I have yet to get a chance to travel outside of the States ever since I moved; traveling might have to wait until school is over.';
echo 'I am currently majored in IT concentrated in DTP and working as a junior network engineer for a MSSP.';
echo '</p>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<!--#include virtual="ssi/copyrights.txt"-->';
echo '</div>';
echo '';
echo '</div>';
echo '</body>';
echo '</html>';
?>